<a href="https://colab.research.google.com/github/Priti-Kannaujiya/DeepLearning-FromScratch/blob/main/SentimentAnalysis(CNN_LSTM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
9import kagglehub
path = kagglehub.dataset_download("ashirwadsangwan/imdb-dataset")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/ashirwadsangwan/imdb-dataset?dataset_version_number=877...

100%|██████████| 1.64G/1.64G [00:12<00:00, 143MB/s]

Extracting files...

In [ ]:
import os
os.listdir(path)

['name.basics.tsv',
 'title.basics.tsv',
 'title.principals.tsv',
 'title.ratings.tsv',
 'title.akas.tsv']

In [ ]:
import pandas as pd
basics = pd.read_csv(path + "/title.basics.tsv", sep="\t")
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [ ]:
rating = pd.read_csv(path + "/title.ratings.tsv", sep='\t')
rating.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2198
1  tt0000002            5.5       310
2  tt0000003            6.5      2304
3  tt0000004            5.1       196
4  tt0000005            6.2      3035

In [ ]:
df=basics.merge(rating,on='tconst')

In [ ]:
df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",5.7,2198
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short",5.5,310
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance",6.5,2304
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short",5.1,196
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short,6.2,3035

In [ ]:
df.isnull().sum()

tconst            0
titleType         0
primaryTitle      2
originalTitle     2
isAdult           0
startYear         0
endYear           0
runtimeMinutes    0
genres            4
averageRating     0
numVotes          0
dtype: int64

In [ ]:
df.shape

(1646044, 11)

In [ ]:
df=df[['primaryTitle','genres','averageRating']]
df=df.dropna()

In [ ]:
df.shape

(1646038, 3)

In [ ]:
df['label'] = df['averageRating'].apply(lambda x: 1 if x >= 7 else 0)

In [ ]:
df.head()

             primaryTitle                    genres  averageRating  label
0              Carmencita         Documentary,Short            5.7      0
1  Le clown et ses chiens           Animation,Short            5.5      0
2            Poor Pierrot  Animation,Comedy,Romance            6.5      0
3             Un bon bock           Animation,Short            5.1      0
4        Blacksmith Scene                     Short            6.2      0

In [ ]:
df['label'].value_counts()

label
1    937688
0    708350
Name: count, dtype: int64

In [ ]:
len(df['genres'].unique())

2072

In [ ]:
df = df.explode('genres')
df = pd.get_dummies(df, columns=['genres'])

In [ ]:
df.head()

,primaryTitle,averageRating,label,genres_Action,"genres_Action,Adult","genres_Action,Adult,Adventure","genres_Action,Adult,Animation","genres_Action,Adult,Comedy","genres_Action,Adult,Crime","genres_Action,Adult,Drama",...,"genres_Sport,Talk-Show","genres_Sport,Thriller","genres_Sport,War",genres_Talk-Show,genres_Thriller,"genres_Thriller,War","genres_Thriller,Western",genres_War,genres_Western,genres_\N
0,Carmencita,5.7,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Le clown et ses chiens,5.5,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Poor Pierrot,6.5,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Un bon bock,5.1,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Blacksmith Scene,6.2,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.shape

(1646038, 2075)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
texts = df['primaryTitle']
tokenizer = Tokenizer(num_words=10000)       # we are taking top 10000 words that are appearing frequently
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

In [ ]:
sequences

[[],
 [63, 1290, 269, 7399],
 [1494],
 [107, 2481],
 [1308],
 [1705, 368],
 [6, 7239, 315, 1],
 [1629, 3, 5, 9349],
 [354, 1466],
 [1917, 1, 1322],
 [],
 [1, 2196, 3, 5, 455],
 [1, 8534, 5339, 7],
 [1],
 [606, 5, 1821],
 [1289, 1917, 1, 2869],
 [],
 [149],
 [1, 1290, 4067],
 [1, 3214],
 [1308],
 [1, 192],
 [1618, 3, 1, 4368],
 [1, 9486, 6, 3900, 1289, 362],
 [1, 8869, 28, 2621],
 [1712, 7],
 [1898, 14, 6771],
 [7555, 4252],
 [1994, 192, 28, 9636],
 [4686, 1, 6088],
 [43],
 [603, 1286, 2053],
 [2377, 455, 13],
 [1, 1183],
 [1342, 3, 4088],
 [192],
 [1, 457, 74],
 [603, 848],
 [175, 2869, 13],
 [13],
 [1437, 18, 6089],
 [347],
 [63],
 [118],
 [9113, 13],
 [6509, 177],
 [1, 3200, 6041],
 [3200, 613, 71, 7320, 1858],
 [269],
 [1],
 [670],
 [5, 69, 347, 1948, 69, 8216],
 [5, 1204, 89, 471],
 [63],
 [1657, 13, 12, 9487],
 [13, 347, 9793],
 [13, 670, 9113, 13],
 [6260, 3, 5, 923, 2925],
 [784],
 [784, 122],
 [5543],
 [938],
 [],
 [7917, 2171],
 [556],
 [145, 648, 5258, 7, 5136, 1879],
 [1, 1289],
 [1440, 12, 7400],
 [5928, 3, 5, 641],
 [3548, 5, 362],
 [3, 994, 1205, 1917, 962],
 [13, 4068, 1437, 118],
 [4611, 1437, 18],
 [1, 8757, 3, 5, 155, 28, 1, 56, 3, 777],
 [1637, 3, 4088, 6, 1, 6379],
 [63, 8012],
 [13, 170],
 [18, 981],
 [8319],
 [5, 1289, 16, 1, 380],
 [5, 300, 3730],
 [118],
 [118],
 [9233, 864],
 [480, 6, 7321, 28, 3412, 11],
 [480, 6, 7321, 28, 2822, 11],
 [2095, 29],
 [1917, 4276, 78, 3215],
 [177],
 [1, 56, 3, 1, 309],
 [1437],
 [8987],
 [354, 13],
 [1, 902, 1076],
 [303, 981],
 [303, 13, 83, 839],
 [303, 13, 298, 839],
 [303, 13, 18],
 [303, 13, 18],
 [303, 175],
 [1, 480, 28, 7, 5],
 [431, 1, 976],
 [347],
 [1, 28],
 [4199, 670],
 [9954, 1256, 28],
 [4088, 1917, 5382, 2447],
 [4088, 674, 1, 6379],
 [4088, 2926, 161, 1, 418],
 [4339],
 [4339, 9, 3432],
 [1252, 890],
 [994, 384, 9, 1, 1128],
 [],
 [670, 964],
 [69, 246],
 [2377],
 [533, 16, 1, 380, 1295, 8],
 [533, 16, 1, 380, 1295, 4],
 [1, 6380, 7556],
 [3621, 782, 28, 8108, 1322],
 [8757],
 [1437, 18, 175],
 [1, 1680, 3215, 2535],
 [489, 132, 3180],
 [118, 2377],
 [970, 14, 227, 1168],
 [107, 3080, 9114],
 [730, 670, 2763],
 [5, 1680, 34],
 [1503, 114],
 [18, 175],
 [1, 4369, 3659],
 [5, 8320, 2076],
 [670],
 [1, 8013, 2402],
 [],
 [1253, 63],
 [2823],
 [2283, 572, 6, 5259],
 [118],
 [3259, 63],
 [86],
 [63, 13],
 [1, 232],
 [63],
 [209, 1, 574],
 [5543, 13, 3974],
 [5778, 269],
 [1, 7717],
 [1, 542, 618],
 [],
 [1, 28, 547],
 [5, 8988, 483],
 [],
 [],
 [1, 776],
 [1, 47, 140, 3, 7401],
 [13, 5543],
 [7557, 1144],
 [63, 175, 4643],
 [63, 1253, 63],
 [86, 107, 2763],
 [13, 160, 13, 18, 6841, 7240],
 [13, 13, 113, 13],
 [113, 13, 18, 13, 663, 4401, 13, 2536],
 [15, 5632],
 [1, 1271, 114],
 [730, 2230],
 [1, 206, 1119, 7631],
 [111, 3, 6381, 1370],
 [5],
 [5, 192, 1713, 2824, 8535],
 [],
 [1, 6510, 16, 1, 2378],
 [1, 131],
 [1, 1713, 3, 1, 1523],
 [63, 13],
 [2042],
 [244, 1407, 69],
 [1, 390],
 [1603, 953, 245, 1308],
 [18, 347],
 [63, 6261],
 [18],
 [1],
 [],
 [1731],
 [347, 18, 13, 9113],
 [3859, 2898, 5, 18],
 [347],
 [938, 455, 16, 5, 3215, 3901],
 [118, 13],
 [5778, 6],
 [18],
 [18, 86],
 [9637, 127, 4011],
 [1833, 13],
 [1296, 75, 5056],
 [63, 177],
 [895, 2870, 168],
 [],
 [13],
 [13, 107, 5, 18, 13, 113, 8989, 13, 3127],
 [625, 938],
 [1, 2231, 6, 6919],
 [5, 166],
 [5, 28, 206],
 [1, 131, 71, 1, 25, 7, 1, 212],
 [69, 13],
 [],
 [137, 1, 2284, 2275],
 [5],
 [9955, 13, 4401, 168, 6316, 5, 3127],
 [2276, 6],
 [6511, 8870],
 [5497, 6, 1, 1148, 4115],
 [1, 1449, 6, 1, 1048, 58],
 [246, 13],
 [670, 5057],
 [],
 [3026],
 [459, 6, 1, 445],
 [1289, 362],
 [3],
 [18, 9488],
 [4687, 28, 1, 2188],
 [2042],
 [3215, 455],
 [63],
 [13, 964],
 [2096],
 [360, 1, 3, 127],
 [],
 [63],
 [118, 13],
 [5543, 2514, 621, 2764],
 [5, 75, 1714],
 [18, 13],
 [1, 2172, 3, 1, 885],
 [],
 [1, 542, 56],
 [5, 934, 3, 1, 1151],
 [98, 173],
 [5, 375, 7, 1, 1872],
 [1, 590],
 [113, 5],
 [5724, 50, 7073],
 [18],
 [1, 1213],
 [13],
 [2377],
 [4859, 30, 1, 1008, 3, 1, 2157, 712],
 [18],
 [63, 13],
 [63],
 [],
 [5, 550, 2],
 [107, 1834],
 [5875, 13, 18, 6434, 13, 18, 5220, 13, 13, 38, 2295, 13],
 [1, 1835],
 [1391, 1, 2431],
 [1391, 1],
 [],
 [],
 [1205, 32, 71, 91, 2097, 81, 385],
 [],
 [13, 269],
 [163, 1918, 371, 5],
 [366, 16, 5, 984, 449],
 [3155, 13],
 [],
 [13, 13],
 [2283, 8536, 51, 1128],
 [2283, 8536, 129, 332, 1128],
 [2283, 8536, 129, 332, 1128],
 [2283, 8536, 129, 332, 51],
 [63],
 [3259, 63],
 [3259, 63],
 [1705, 205],
 [2345, 13],
 [1, 1290, 6, 1, 7717],
 [18],
 [3570],
 [228, 13],
 [1253, 118],
 [5543, 175],
 [18, 5543, 175],
 [5543, 175],
 [5543],
 [],
 [5725],
 [63, 269, 13],
 [1, 2871, 4612],
 [5778, 6],
 [18, 2432, 1760, 18, 177, 4611],
 [],
 [6641, 3731, 822],
 [],
 [3622, 1002, 1308, 20],
 [197],
 [1, 56, 70, 321, 2510],
 [91, 36, 3902, 9, 68, 229, 161],
 [6, 1, 8871],
 [63],
 [416, 27, 131, 223],
 [13, 5543],
 [63, 13, 5593],
 [347, 18],
 [63],
 [867, 556, 2885],
 [7918, 3775],
 [2061],
 [1, 4277, 2331],
 [4859, 13, 3127, 168],
 [1311],
 [1311, 13],
 [1311, 177],
 [1311, 175],
 [18],
 [18, 4116],
 [63],
 [18, 6842],
 [18, 7917, 177],
 [4199, 177, 7478],
 [63, 3163, 347, 18, 532, 3164],
 [2097, 3, 1, 885],
 [18, 4489],
 [2284],
 [3201, 13, 18, 5543],
 [18],
 [831, 1487, 7, 5, 3832, 483],
 [831, 450],
 [730, 1134, 13],
 [],
 [],
 [],
 [403, 441, 14, 1, 7558],
 [2283, 8536, 129, 332, 1128],
 [],
 [79, 794, 49, 3, 1, 1937, 71, 1, 7, 5, 37, 472, 1844],
 [1, 83, 1445, 3, 1, 2043, 2358],
 [],
 [29, 28, 1, 919],
 [3860, 3, 20, 4859, 3, 954],
 [13, 12, 13],
 [127],
 [],
 [1, 542, 7322, 998],
 [304, 3, 5, 414],
 [1, 1206, 5177, 465],
 [],
 [1497, 742],
 [4859, 3, 78, 34],
 [1311, 13],
 [62, 94, 1970, 1219],
 [8217, 71, 166],
 [1, 776, 391, 7241],
 [5],
 [2837],
 [9955, 13, 18, 5, 3127],
 [1176, 459],
 [2283, 8536, 129, 332, 51],
 [354, 6, 157, 9794, 584],
 [18, 177, 3165],
 [1, 6260, 3, 98, 2706, 3141],
 [5543],
 [18],
 [321, 6, 1, 6202],
 [63, 999],
 [63, 13],
 [259, 2707, 6203, 6772],
 [63],
 [1331, 18],
 [18, 9350],
 [1, 478, 3, 426],
 [13, 316, 13, 4401, 13, 18, 13, 2536],
 [],
 [9, 1, 5498],
 [6, 1327, 46, 1, 90, 1197],
 [4227, 7919],
 [1, 8430, 645],
 [1, 776, 253, 7242],
 [831, 1487, 28, 1, 1102, 855, 51],
 [5],
 [8014, 6, 2062, 4939],
 [5, 409, 9, 1, 212],
 [1, 129, 25, 3],
 [],
 [1022, 7, 1955],
 [118, 1311],
 [118, 9638, 2377, 7074],
 [1, 2871, 377],
 [118],
 [2283, 8536, 1128],
 [2283, 8536, 204, 1128],
 [977, 626, 13, 18],
 [13, 86, 38],
 [18, 8872, 670],
 [5, 4340],
 [91, 3713, 601, 150, 2379],
 [13, 1196],
 [131],
 [86, 269, 8321],
 [50, 2837, 6204, 2535],
 [5778, 6],
 [63, 9234],
 [1, 95, 455, 2034],
 [18],
 [86, 38, 8537, 13, 160],
 [2599, 3860],
 [],
 [],
 [4490, 5178],
 [32, 3, 50, 136, 8655],
 [63, 175],
 [18, 1260, 175, 4644, 1760, 63, 4801, 177, 3679],
 [569],
 [1, 3714, 6435, 2537],
 [1, 225, 1161],
 [731, 168, 127, 5383, 6642],
 [4859, 3, 156, 731, 168],
 [1, 6205],
 [5929, 13, 3127],
 [4088, 314],
 [1, 705, 3, 1, 7149],
 [962],
 [1, 1675, 4940],
 [831, 8322, 1821],
 [831, 8322, 1821],
 [18],
 [1196, 3, 1],
 [8871, 33],
 [63],
 [1, 95, 455, 2034],
 [1, 226, 263, 1, 1702],
 [1618, 1, 712],
 [1614],
 [1, 2088, 4941],
 [4578],
 [5, 3215, 1706],
 [78, 7001],
 [50, 1202, 1196],
 [1],
 [260, 3, 2266, 1681],
 [],
 [13, 827, 168],
 [168, 13, 663, 168, 13],
 [1, 1025],
 [1, 2993, 3, 240, 924],
 [3975, 3, 6, 1, 8538, 30, 37, 472],
 [38, 5, 18, 8015, 168, 13],
 [1],
 [38, 13, 18],
 [],
 [1575, 3],
 [168],
 [160, 13, 18, 113],
 [38, 13, 1035],
 [1, 1524, 483],
 [38],
 [1],
 [1, 32, 3, 1484, 821],
 [1, 62, 455, 2034],
 [1],
 [37, 472, 4894],
 [3230, 28, 9489, 92],
 [8539, 1872],
 [1, 4772],
 [7, 1, 5384],
 [405, 246, 13],
 [160, 13, 5876],
 [168, 18, 168, 13],
 [1, 6, 252, 3, 5],
 [1, 2215, 2215],
 [1, 259, 7, 486],
 [],
 [2196, 3, 4645, 156],
 [],
 [1152, 2600, 297],
 [1, 131],
 [131, 3, 5, 7631],
 [15],
 [4707, 1152, 297, 3715],
 [1, 493, 3, 1, 1449],
 [1, 542, 483],
 [3, 935, 1030],
 [368],
 [],
 [1, 32, 3, 5, 1319],
 [1441],
 [1, 34, 315, 61],
 [1, 7920, 2494, 3, 1, 309],
 [876],
 [456, 2392, 1043],
 [1, 456, 2392, 5459],
 [1, 39, 3, 1, 1343, 743],
 [164, 694, 8540, 201, 1, 192],
 [1504, 2346, 6, 1, 3081, 1747],
 [50, 5633, 4895, 71, 1, 7921, 16],
 [1, 2910, 869, 88],
 [5, 149, 8656, 12, 9487, 1450],
 [169],
 [659],
 [1, 207, 20, 1],
 [38, 13, 18],
 [5, 2119, 131],
 [45, 3037],
 [310],
 [1, 3812, 234],
 [1, 571, 30, 1],
 [30, 1, 627],
 [],
 [1, 205, 812],
 [3622, 478, 3, 6578],
 [3640, 466, 435],
 [],
 [999, 1083],
 [1, 205, 4341, 3526],
 [117, 1049, 6, 779],
 [86, 4708, 1193, 1608],
 [9351],
 [9351],
 [7, 1, 202],
 [55, 13, 1657],
 [1, 94, 9795],
 [2034, 201, 1624],
 [1, 4835],
 [],
 [70, 1038, 9349],
 [1, 205, 1650],
 [3680],
 [507],
 [1, 260, 3],
 [162, 868, 274],
 [3622],
 [3622],
 [17, 70, 2601],
 [6, 4802],
 [163, 23, 110, 36],
 [1, 3527, 3, 1, 2482, 13],
 [28, 1, 2696, 3, 32],
 [28, 1, 994, 457],
 [50, 5633, 856],
 [28, 1, 5460],
 [1],
 [2622, 1, 39, 3, 5, 136, 155],
 [209, 1, 574],
 [4228, 78, 5],
 [574],
 [1, 67, 8541],
 [],
 [1, 2414, 1271, 114],
 [1, 119, 689, 71, 1],
 [5],
 [1, 231, 3, 1, 129],
 [1, 450],
 [1323, 78],
 [1, 61],
 [4173, 371, 1, 3501],
 [],
 [1, 6, 1, 5260],
 [5, 6510],
 [13, 526, 3623],
 [1, 797, 3, 3027, 5634],
 [6579],
 [],
 [1, 309],
 [18, 8758],
 [726, 2111],
 [726],
 [726, 55, 18, 113],
 [1, 6, 1135, 2460],
 [5261],
 [5, 1689, 327],
 [5, 1039],
 [1, 1038, 527],
 [296, 387, 7, 1, 74],
 [1, 2439, 6, 1, 2044],
 [5, 2838, 2439, 71, 17, 7, 1],
 [14, 17, 3, 254],
 [14, 5, 5594, 939],
 [38, 13],
 [1, 58, 6, 1, 2538],
 [1, 4491],
 [1],
 [1, 120, 3, 55, 8109],
 [1, 5262, 493],
 [157, 83, 276],
 [985],
 [1, 919],
 [1, 6580],
 [1],
 [1, 903],
 [5877, 3732],
 [1],
 [98, 3, 1, 3433, 2296],
 [1, 1919, 3714],
 [1, 8431],
 [1, 32, 3, 50, 136, 1319],
 [4942],
 [1, 25, 6, 1, 155],
 [1, 94, 3413, 181],
 [1, 5179, 3, 2495],
 [3100, 1981],
 [1625, 655, 7, 5, 8323, 156, 809, 1244],
 [253, 555],
 [117, 619, 28, 1, 457],
 [779, 619],
 [1, 225, 415],
 [132, 1],
 [9351],
 [1, 2538],
 [161, 1, 660, 9, 1],
 [1, 520, 1193],
 [38, 13],
 [1, 254],
 [1, 427],
 [1, 407, 7, 1],
 [5058, 3776],
 [1, 1761],
 [1, 58],
 [1, 94, 25, 6, 1, 417],
 [30, 50, 1949],
 [901, 398],
 [629, 3, 5],
 [1753, 6, 2754],
 [1, 131, 3, 50, 7631],
 [1, 450],
 [360],
 [2266, 1681],
 [2266, 1681, 106, 30, 954],
 [2266, 1681, 398, 1, 276, 7, 1, 2802, 7718],
 [5, 1223],
 [1, 275, 3, 1, 3921],
 [1, 1003],
 [1, 1324, 6512],
 [],
 [598, 3, 67, 282],
 [1, 4836, 3, 1],
 [1, 513],
 [1, 535, 3, 1488],
 [1036],
 [1, 47, 140, 3, 7401],
 [1, 427],
 [1, 4860],
 [1, 513, 1, 39, 3, 1, 1044],
 [5, 1297, 9, 1, 6773, 28, 6513, 480, 1550],
 [135, 189, 7, 1048],
 [135, 1633, 661, 4861],
 [216, 1, 6703, 4278],
 [],
 [5, 2856, 133],
 [1, 1224, 3454],
 [1, 120],
 [1, 111, 7, 1, 1854],
 [6, 5, 62, 417, 1859, 2666, 853],
 [],
 [28, 1, 5460],
 [50, 8759, 9, 3202, 5, 1220],
 [1, 1342],
 [5, 7555, 3455],
 [1, 417],
 [38, 113, 6262],
 [],
 [1, 514, 133],
 [572, 47, 74],
 [38],
 [18, 13, 2839, 5930],
 [1, 1124],
 [1, 440],
 [5, 1498, 9, 4896],
 [5, 2537],
 [1, 1225],
 [5, 595, 3, 120],
 [1, 3798, 258],
 [9956, 5, 1223],
 [1],
 [5878],
 [5, 1732],
 [1, 3, 32],
 [5, 2315, 7],
 [1, 388, 444],
 [1, 3376, 16, 1],
 [1441, 1587, 13],
 [1, 1974],
 [5, 69],
 [1, 2393, 2166],
 [1, 29, 162],
 [13, 5, 3127],
 [1, 57, 7075, 5, 39, 3, 1, 4520],
 [1, 57, 3, 3549, 1, 1680],
 [1, 1986],
 [107, 2295, 86],
 [726, 2111],
 [1, 2857, 3, 5, 7402, 716],
 [160, 964, 8657],
 [1, 747, 14, 5, 32],
 [5],
 [1],
 [3756, 7002, 8218],
 [20, 9352],
 [13, 160],
 [7922],
 [1],
 [113, 86, 13],
 [1],
 [5, 848, 2288],
 [],
 [1, 779, 3733],
 [7719],
 [3876, 13],
 [13, 663],
 [86, 18],
 [5, 5422, 305],
 [2207, 3, 849],
 [],
 [1, 994, 1002],
 [1, 258, 3, 1, 76],
 [800, 1281],
 [1, 2423],
 [13, 168],
 [1, 122, 6, 774],
 [1, 306, 1383],
 [1, 1690, 207],
 [1, 94, 5292],
 [38],
 [3622, 478, 3, 6578],
 [8016, 6, 7003],
 [1, 120, 3, 50, 2538],
 [2780, 975, 6, 1, 604],
 [157, 83, 9490],
 [157, 1296, 267],
 [1, 9353],
 [1, 6514],
 [150, 1384],
 [150, 80, 17],
 [150, 17],
 [150, 5594, 259],
 [150, 5594, 2529],
 [1, 939, 3, 1747],
 [1, 56, 3, 2621],
 [15, 729, 36],
 [7, 132, 5059],
 [7, 1, 7076, 3, 1, 34],
 [7, 1, 1473],
 [1, 1296, 629],
 [895, 107],
 [1],
 [619, 6, 150, 37, 2825],
 [619, 6, 1, 207, 470, 1141],
 [1, 184, 4772],
 [5, 100, 139],
 [13, 106],
 [98, 7720],
 [1754],
 [45, 3156],
 [],
 [5, 155, 3, 1, 220],
 [207],
 [4646],
 [1, 233, 70, 794],
 [1434, 3, 126, 16, 5, 192],
 [1, 62, 2347],
 [1, 62, 976],
 [13, 615],
 [1, 1198, 2316],
 [17, 2658, 5, 133],
 [1, 883, 3, 1, 2621],
 [664, 906],
 [1, 8542, 3, 1],
 [4897],
 [4942],
 [4492],
 [1, 5340, 1807],
 [8321],
 [1, 2469, 2322],
 [168, 38],
 [1],
 [1, 1498],
 [1, 2978, 9491],
 [5, 550, 276],
 [5, 4253, 3082, 131],
 [1, 9235, 3, 1, 1122],
 [118],
 [1, 32, 3],
 [1, 3681],
 [1, 939],
 [117, 619, 468, 5, 1503, 114],
 [117, 6510],
 [779, 1161, 71, 378, 22],
 [4896, 876, 3260],
 [4896, 1, 25, 3, 870],
 [1, 7243],
 [9796, 86, 18],
 [1, 2500, 7, 1, 3455],
 [5, 8541],
 [91, 423, 1807, 189, 5, 1274],
 [1, 607],
 [511, 831],
 [2297, 1840],
 [16, 1, 62, 48, 4370, 71, 47, 522],
 [13, 9957],
 [31, 4089, 527],
 [31, 925, 3, 1031],
 [308, 5, 5260],
 [1, 609, 1570],
 [9351],
 [481, 870],
 [1, 1193],
 [71, 1, 275, 3, 4748],
 [1, 17, 39],
 [6579],
 [18, 6436, 168],
 [1, 478, 6, 1],
 [407, 71, 1, 1184, 1178],
 [13, 107, 9639, 13, 86, 38, 13],
 [1, 741],
 [1, 839],
 [1],
 [1, 5595],
 [1852],
 [5, 252, 6437, 1, 994, 632],
 [1, 112, 9, 1, 120],
 [5, 8017, 8873],
 [5, 9640],
 [1, 1732],
 [555],
 [1, 3799, 1205],
 [1, 4943, 245],
 [1, 3357, 29],
 [360, 1270, 68, 50, 4279],
 [2266, 1681, 1079],
 [2266, 1681, 195],
 [2266, 1681, 1236],
 [5, 4312, 17, 5, 261, 3, 1, 3833, 75],
 [1, 2602],
 [1197],
 [1, 9958, 148],
 [5, 4253, 3082, 131],
 [],
 [5, 538, 674],
 [38, 5293],
 [1, 1667, 251],
 [5, 292, 305],
 [292, 6, 1252],
 [3470, 620],
 [1, 535],
 [318, 1270],
 [1096, 5633, 5258],
 [1096, 249],
 [371, 1, 6703],
 [2603, 50, 4430, 531, 70, 4371, 12, 88],
 [13, 9],
 [9, 451, 157, 469],
 [113],
 [4898, 17],
 [5, 610, 14, 663, 2781],
 [1, 1286, 70, 7479],
 [5, 8430],
 [3550, 9, 158, 9641],
 [1643, 390],
 [60, 690],
 [60, 248, 6, 5, 25],
 [60, 3, 1, 249],
 [18, 840, 86, 38],
 [13, 8758],
 [1, 5975, 2332, 3],
 [1, 829, 3, 1, 5975],
 [968, 5, 417],
 [189, 389, 4647],
 [1604, 201, 1, 136, 2275],
 [1, 133, 3, 25],
 [72, 862, 69, 147, 109],
 [1, 286, 6510],
 [79, 2515, 729],
 [591, 52, 7323],
 [1, 2394, 4648],
 [20, 157, 1503],
 [1, 6206, 2470],
 [5, 7, 42],
 [5976],
 [50, 540, 3, 620],
 [1, 540, 3, 50, 1263],
 [1, 155, 644, 4521],
 [8658, 260, 7, 1955],
 [40, 16, 8432, 3, 1, 1736],
 [],
 [],
 [3622],
 [615],
 [15],
 [106],
 [4802],
 [50, 2007],
 [163, 36, 21, 7, 32],
 [163, 1, 2424, 6515, 49],
 [1, 94, 2402],
 [1, 2216],
 [1, 440, 1153],
 [2283, 8536, 129, 332, 6, 8536, 682, 904],
 [78, 945, 3, 4896],
 [1, 231, 9, 1624],
 [1, 231],
 [],
 [5, 417, 3, 1, 4899],
 [5, 3414, 832],
 [5, 3414, 9492],
 [5, 3414],
 [1, 925],
 [1, 5977],
 [1],
 [1, 1558, 3, 285, 17],
 [7324],
 [1, 784, 58, 3],
 [8543],
 [726, 2111, 13],
 [],
 [4773, 6, 1, 4749, 7, 2765],
 [1, 630],
 [],
 [],
 [],
 [1, 6, 1, 58],
 [29, 28, 144],
 [211],
 [1, 283, 28, 1, 1473],
 [6774],
 [5778],
 [1, 4860, 71, 513],
 [1, 105],
 [5, 2030, 3, 233],
 [5, 1217, 567],
 [2167],
 [1, 2842],
 [2766, 507],
 [1, 58, 30, 2963],
 [1, 58, 16, 1975, 206],
 [254, 21, 65, 40],
 [5, 254, 7243],
 [1, 254, 7923],
 [1, 306, 3716],
 [3622],
 [3622],
 [3622],
 [157, 1680, 6843],
 [150, 2403, 427],
 [150, 541, 7, 486],
 [1, 939, 3, 150, 76],
 [1, 56, 20, 2404],
 [1, 126, 2602, 2303],
 [1],
 [7, 4174, 2780],
 [7, 132, 1596],
 [7, 1, 1560, 2189],
 [],
 [8990, 78, 34],
 [1, 226, 3, 2765],
 [1, 47, 649],
 [1, 1274],
 [1, 32, 3, 5341],
 [17, 1063, 1, 1808],
 [17, 3],
 [3777, 442, 1956, 297],
 [4942],
 [1, 25],
 [1, 1178],
 [1, 5978, 42, 1422],
 [495, 6, 1267],
 [269],
 [284, 277],
 [1, 1498, 3, 1, 5975],
 [345],
 [5, 550, 3695],
 [1, 1319, 2496],
 [1, 1075, 3812],
 [5, 1070, 7244, 71, 1, 8324, 3, 1],
 [2245, 5, 267],
 [83, 4835],
 [176, 223],
 [1, 37],
 [1],
 [5, 34, 7, 495],
 [1, 3983, 6, 1, 25],
 [16, 1, 5096],
 [1253],
 [161, 558, 6152],
 [],
 [],
 [38],
 [107],
 [13, 13, 8110],
 [],
 [980, 7720],
 [980, 7720],
 [5, 1629, 2952, 371, 625],
 [4774, 556, 1173, 106, 6775],
 [5, 9115, 30, 2217],
 [5, 965, 305],
 ...]

In [ ]:
max_len = max([len(x) for x in sequences])
max_len

48

In [ ]:
sequences=pad_sequences(sequences,maxlen=max_len,padding='post')

In [ ]:
sequences[:5]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [  63, 1290,  269, 7399,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [1494,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [ 107, 2481,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [1308,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]], dtype=int32)

In [ ]:
len(tokenizer.word_index)

375438

In [ ]:
y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    sequences, y, test_size=0.2, random_state=42
)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=128, input_shape=(48,)))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(64))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 48, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 46, 64)         │        24,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 23, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,341,889 (5.12 MB)

 Trainable params: 1,341,889 (5.12 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history=model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

Epoch 1/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 368s 9ms/step - accuracy: 0.5759 - loss: 0.6730 - val_accuracy: 0.5917 - val_loss: 0.6620
Epoch 2/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 392s 10ms/step - accuracy: 0.6013 - loss: 0.6560 - val_accuracy: 0.5946 - val_loss: 0.6607
Epoch 3/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 386s 9ms/step - accuracy: 0.6117 - loss: 0.6477 - val_accuracy: 0.5936 - val_loss: 0.6602
Epoch 4/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 433s 9ms/step - accuracy: 0.6204 - loss: 0.6399 - val_accuracy: 0.5940 - val_loss: 0.6624
Epoch 5/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 370s 9ms/step - accuracy: 0.6276 - loss: 0.6324 - val_accuracy: 0.5900 - val_loss: 0.6646
Epoch 6/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 356s 9ms/step - accuracy: 0.6353 - loss: 0.6247 - val_accuracy: 0.5915 - val_loss: 0.6720
Epoch 7/10
41151/41151 ━━━━━━━━━━━━━━━━━━━━ 349s 8ms/step - accuracy: 0.6415 - loss: 0.6180 - val_accuracy: 0.5903 - val_loss: 0.6735
Epoch 8/10
 6385/41151 ━━━━━━━━━━━━━━━━━━━━ 4:21 8ms/step - accuracy: 0.6518 - loss: 0.6046